apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lszomor-lszomor-poi-gateway-app-dev
  annotations:
    argocd/app-name: lszomor-lszomor-poi-gateway-app-dev
    backstage.io/kubernetes-id: lszomor-lszomor-poi-gateway-app-dev
    backstage.io/kubernetes-namespace: lszomor
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=lszomor-lszomor-poi-gateway-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/lszomor-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/lszomor/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/lszomor/deployments/lszomor-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/lszomor-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/lszomor"
  system: workshop-system-lszomor
  providesApis:
    - gateway-api-lszomor
  consumesApis:
    - backend-api-lszomor
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-lszomor
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/lszomor"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-lszomor
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://lszomor-poi-gateway-app-lszomor.apps.summit23blues.6mbu.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/Summit23Janus2/lszomor-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/lszomor"
  system: workshop-system-lszomor
  definition:
    $text: https://github.com/Summit23Janus2/lszomor-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
